{
    "name": "Envia.com",
    "version": "19.0.1.111.0",
    "category": "Inventory/Delivery",
    "summary": "Quote, create and track Envia.com shipments from Odoo",
    "author": "Alejandro Prado",
    "license": "LGPL-3",
    "depends": ["base", "mail", "onboarding", "sale", "stock", "sale_stock", "envia_http"],
    "data": [
        "data/ir_sequence_data.xml",
        "security/envia_security.xml",
        "security/ir.model.access.csv",
        "data/ir_cron_data.xml",
        "data/envia_carrier_data.xml",
        "data/envia_oauth_config_data.xml",
        "data/envia_demo_data.xml",
        "data/envia_onboarding_data.xml",
        "views/res_config_settings_views.xml",
        "views/res_users_apikeys_views.xml",
        "views/envia_quote_views.xml",
        "views/envia_shipment_views.xml",
        "views/sale_order_views.xml",
        "views/stock_picking_views.xml",
        "wizards/envia_quote_wizard_views.xml",
        "wizards/envia_create_shipment_wizard_views.xml",
        "wizards/envia_plugin_connect_wizard_views.xml",
        "wizards/envia_quote_onboarding_wizard_views.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "envia/static/src/scss/envia_wizards.scss",
            "envia/static/src/js/envia_api_key_field.js",
            "envia/static/src/xml/envia_api_key_field.xml",
            "envia/static/src/js/envia_plugin_connect_wizard_form.js",
            "envia/static/src/components/envia_onboarding/**/*",
            "envia/static/src/views/envia_quote_list/**/*",
        ],
    },
    "images": [
        "static/description/icon.png",
    ],
    "installable": True,
    "application": True,
    "post_init_hook": "post_init_hook",
    "post_load": "post_load",
    "pre_init_hook": "pre_init_hook",
}
